### PR TITLE
Added mock tests for querying

### LINKED ISSUE #88: Mocking is done improperly
## Current Behaviour:
Mocking is being done improperly.
```python
        check_data = [['p.properties', 'p.id', 'p.type'],
                      ["['Location']",'vocab:EntryPoint/Location','Location']]
        query = "show classEndpoints"
        EndpointQuery_get_classEndpoints = MagicMock(return_value=check_data)
        data = EndpointQuery_get_classEndpoints(query)
        print("testing classEndpoints...")
assert data == check_data
```
Correct me if I am missing something, but it seems like this test will always pass, same goes for all the tests. I can't understand why are we mocking Queries?
## Expected Behaviour:
As far as I know we are using moking so we can test the code without calling an actual (server) API, in that case I think we should only mock calls to the server(`url.get()`).

### PR DESCRIPTION
**Pull request by ShravanDoda**
Fixes #88

Mock tests for querying in `python-hydra-agent` have been added. @sandeepsajan0 kindly review

### CODE REVIEW

**Comment by Mec-iS** [comment]
This looks ok to me.

Please @xadahiya @sandeepsajan0 take a look

**Comment by Mec-iS** [comment]
@ShravanDoda Please add docstrings to test cases

**Comment by sandeepsajan0** [comment]
@ShravanDoda  Can you please provide a screenshot of passing test cases? Other things are looking fine.

**Comment by Mec-iS** [comment]
Tests passed in Travis

**Pull request merged**
